### ISSUE TITLE
redirect from make a wishlist to home

### ISSUE THREAD

**Issue by thirionlogan** [thirionlogan/amazonia#10]
Blocked by #6 and #8

When the user saves, redirect them to the home page
Add the X icon to the form, which will also redirect the user to the home page without saving

![web form](https://user-images.githubusercontent.com/73679754/102533492-1dc41480-406b-11eb-8fb4-948f356166af.png)

**Comment by ArtemSilka** [comment]
Hey @thirionlogan , I would like to take on this issue. Let's discuss your expectations!
