### ISSUE TITLE
Make a Wishlist

### ISSUE THREAD

**Issue by thirionlogan** [thirionlogan/amazonia#8]
When I am a User
When I am on the "Make a Wishlist" page
I enter the name of the wishlist
I enter my name into the author field
I enter the first Item which enables another text box for entering another Item
I click the save Icon
it saves (`POST /wishlist`)

Do not worry about redirecting 

[Here](https://material-ui.com/components/material-icons/) is where you can find the save Icon

![web form](https://user-images.githubusercontent.com/73679754/102530861-29154100-4067-11eb-90e7-71b445844402.png)

**Comment by ArtemSilka** [comment]
Hey @thirionlogan , I would like to take on this issue. Let's discuss your expectations!
