### ISSUE TITLE
add an 'add' icon to Home Page

### ISSUE THREAD

**Issue by thirionlogan** [thirionlogan/amazonia#9]
Blocked by #8 and #6 

As a User
I see an 'add' button at the bottom of the page
I click it
I am redirected to the Make a Wishlist page

I would recommend using the `Add` icon from `@material-ui/icons` for the icon and nesting it inside a Floating Action Button or `FAB`. You can import those like this: 
```
import Fab from '@material-ui/core/Fab';
import AddIcon from '@material-ui/icons/Add';
```
you can find the documentation for the Floating Action Button [here](https://material-ui.com/components/floating-action-button/)
you can find the documentation for the Icon components [here](https://material-ui.com/components/icons/#material-icons)

![Home Page](https://user-images.githubusercontent.com/73679754/102533176-ae4e2500-406a-11eb-821e-002688c37963.png)

**Comment by ArtemSilka** [comment]
Hey @thirionlogan , I would like to take on this issue. Let's discuss your expectations!

**Comment by thirionlogan** [comment]
@ArtemSilka Sorry, We're doing this project for a class so we'd like to keep outside contributions to a minimum. Thank you for the interest though!

**Comment by ArtemSilka** [comment]
No problem, thank you for letting me know!
